---
- name: apply calico
  shell: kubectl -s {{ kubernetes_apiserver }} apply -f /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - rbac.yaml
    - calico.yaml

- name: add calico-k8s-network
  shell: calicoctl apply -f /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/calico_ipv4pool_cidr.yaml
