---
- name: stop flannel
  service: 
    name: flanneld
    state: stopped 
    enabled: no
  ignore_errors: true

- name: remove flannel 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/flanneld
    - /etc/sysconfig/flanneld
    - /lib/systemd/system/flanneld.service
    - /usr/libexec/flannel
    - /run/docker_opts.env
    - /run/flannel
