---
- name: stop docker
  service: 
    name: docker
    state: stopped 
    enabled: no
  ignore_errors: true

- name: remove docker 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/docker
    - /usr/bin/docker-containerd
    - /usr/bin/docker-containerd-ctr
    - /usr/bin/docker-containerd-shim
    - /usr/bin/dockerd
    - /usr/bin/docker-init
    - /usr/bin/docker-proxy
    - /usr/bin/docker-runc
    - /tmp/docker-{{ docker_version }}.tgz
    - /tmp/docker
    - /etc/docker
    - /var/lib/docker
