---
- name: add centos7 repo
  yum_repository:
    name: centos7
    description: centos7 YUM repo
    baseurl: "{{ centos7_yum_url }}"
    gpgcheck: no
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7

- name: add ubuntu repo
  apt_repository:
    repo: deb {{ ubuntu_apt_url }} xenial repo
    state: present
    filename: dce-offline.list
  when: ansible_os_family == "Debian" and ansible_distribution == "xenial"
