---
- name: certificate approve csr
  shell: kubectl certificate approve $(kubectl get csr -ojsonpath='{.items[?(@.status.conditions[0].type!="Approved")].metadata.name}';kubectl get csr -ojsonpath='{.items[?(not @.status)].metadata.name}')
