---
- name: delete calico 
  shell: kubectl -s {{ kubernetes_apiserver }} delete -f /var/tmp/calico/{{ calico_version.split('.')[:2] | join('.') }}/{{ item }}
  with_items:
    - calico.yaml
    - rbac.yaml
  async: 10
  ignore_errors: true

- name: remove calico yaml
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/calicoctl
    - /var/tmp/calico
    - /etc/calico
