---
- import_tasks: redhat/redhat_docker_uninstall.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7
- import_tasks: debian/debian_docker_uninstall.yml
  when: ansible_os_family == "Debian" and ansible_distribution == "xenial"
