---
- name: install conntrack-tools
  yum: 
    name: conntrack-tools
    state: present
    update_cache: yes

- name: create dir /var/lib/kubelet
  file:
    path: /var/lib/kubelet
    state: directory
    owner: root
    group: root
    mode: 0755

- name: fetch kubelet binary to PATH(/usr/local/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kubelet"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
  notify: restart kubelet

- name: create kubelet configuration
  template: 
    src: "{{ kubernetes_version.split('.')[:2] | join('.') }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'config.j2', dest: '/etc/kubernetes/config' }
    - { src: 'kubelet.j2', dest: '/etc/kubernetes/kubelet' }
    - { src: 'kubelet.service.j2', dest: '/lib/systemd/system/kubelet.service' }
  notify: restart kubelet

- name: systemd daemon-reload
  systemd: 
    daemon-reload: yes

- name: start kubelet
  service: 
    name: kubelet
    state: started 
    enabled: yes
