---
- name: stop kubernetes-node 
  service: 
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: 
    - kubelet
    - kube-proxy
  ignore_errors: true

- name: filter mounted container dirs
  shell: df
  register: df_result

- set_fact: DF_RESULT={{ df_result.stdout | regex_findall('(/var/lib/kubelet/pods/.+)') }}
- name: unmount left pods
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ DF_RESULT }}"

- name: remove kubernetes-node directories & configurations
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/kubelet
    - /usr/local/bin/kube-proxy
    - /etc/kubernetes/
    - /etc/cni/
    - /opt/cni/
    - /lib/systemd/system/kubelet.service
    - /lib/systemd/system/kube-proxy.service
    - /var/lib/kubelet

- name: uninstall conntrack-tools
  yum: 
    name: conntrack-tools
    state: absent
    update_cache: yes

- name: delete calico 
  shell: >
         kubectl -s {{ kubernetes_apiserver }} -n kube-system delete secrets calico-etcd-secrets \
         && ip link set dev tunl0 down \
         && ip link delete tunl0
  ignore_errors: true

